/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package seminaryclient.vista.paneles;

import java.util.Observable;
import seminaryclient.logica.modelo.ControlConexion;
import seminaryclient.logica.util.ClienteAtributo;
import seminaryclient.logica.util.Notificador;

/**
 *
 * @author Ariel Arnedo
 */
public class PanelChat extends PanelRoot implements java.util.Observer{

    
    
    public PanelChat() {
        initComponents();
        initServices();
    }

    
    private void initServices(){
        Notificador.getNotificador().addObserver(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        areaDeTrabajo = new javax.swing.JTextArea();
        etiNombreHost = new javax.swing.JLabel();
        etiIcon = new javax.swing.JLabel();
        campoChat = createTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        areaDeTrabajo.setEditable(false);
        areaDeTrabajo.setColumns(20);
        areaDeTrabajo.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        areaDeTrabajo.setRows(5);
        areaDeTrabajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255)));
        jScrollPane2.setViewportView(areaDeTrabajo);

        etiNombreHost.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        try{
            etiNombreHost.setText(java.net.InetAddress.getLocalHost().getCanonicalHostName());
        }catch(Exception ex){
            etiNombreHost.setText("XXXXXXXXX");
        }

        etiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seminaryclient/vista/recursos/answer-email-symbol.png"))); // NOI18N

        campoChat.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        campoChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiNombreHost, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(campoChat, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(etiIcon)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiNombreHost, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoChat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiIcon))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoChatActionPerformed
        if(campoChat.getText().compareTo("") == 0){
            return;
        }
        ControlConexion.getInstace().enviarMensaje(ClienteAtributo.MENSAJE_DE_CHAT, campoChat.getText());
        campoChat.setText("");
    }//GEN-LAST:event_campoChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDeTrabajo;
    private javax.swing.JTextField campoChat;
    private javax.swing.JLabel etiIcon;
    private javax.swing.JLabel etiNombreHost;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object obj) {

        if(obj instanceof String){
            System.out.println(String.valueOf(obj));
            areaDeTrabajo.setText((areaDeTrabajo.getText().compareTo("") == 0 ) ? 
                    String.valueOf(obj) : areaDeTrabajo.getText()+"\n"+String.valueOf(obj));

        }
    }
}
